Implementação da funcionalidade "soma"
renilsonjss/GQSO_Rjss pull request #5
Opened 2021-08-20 02:12 UTC by renilsonjss

Foi implementada uma funcionalidade que permite a entrada de dois números e retorna a soma entre eles.

2021-09-08 01:24 UTC, ajosealan requested changes
Poderia deixar a interação com o usuário mais dinâmica.

2021-09-08 01:24 UTC, ajosealan commented on main.go
> +    app.Get("/", func(c *fiber.Ctx) error {
Nessa parte inicial, poderia ser dada orientação ao usuário de como utilizar a calculadora através da URL.

2021-09-11 20:50 UTC, renilsonjss commented on main.go
> +    app.Get("/", func(c *fiber.Ctx) error {
Uma mensagem de orientação foi implementada e é exibida quando o navegador é carregado.

2021-09-14 02:13 UTC, ajosealan approved these changes
Otimo, mudanças importantes.

2021-09-14 02:25 UTC, merged